-- 기존 데이터 초기화 (dev 환경 재시작 시 중복 방지)
TRUNCATE wishlists, tasting_notes, users, whiskies RESTART IDENTITY CASCADE;

-- Whiskies
INSERT INTO whiskies (name_en, name_ko, image_file, alcohol_by_volume, style, country, region, price, nose_tags, palate_tags, body, aftertaste, description, embedding_text, created_at, updated_at) VALUES ('Glenfiddich 12', '글렌피딕 12년', NULL, 40.0, 'Single Malt', 'Scotland', 'Speyside', 55000, ARRAY['APPLE_PEAR', 'HONEY', 'OAK'], ARRAY['VANILLA', 'CREAMY', 'MALT'], 'LIGHT', 'MEDIUM', '입문자에게 추천하는 대표적인 싱글몰트. 가볍고 부드러운 과일향이 특징.', '글렌피딕 12년 싱글몰트 스페이사이드 가벼운 부드러운 과일향 사과 배 꿀 오크 바닐라 크림 몰트 입문용', NOW(), NOW());
INSERT INTO whiskies (name_en, name_ko, image_file, alcohol_by_volume, style, country, region, price, nose_tags, palate_tags, body, aftertaste, description, embedding_text, created_at, updated_at) VALUES ('Macallan 12 Sherry Oak', '맥캘란 12년 셰리오크', NULL, 40.0, 'Single Malt', 'Scotland', 'Speyside', 89000, ARRAY['DRIED_FRUIT', 'CARAMEL', 'VANILLA'], ARRAY['CHOCOLATE', 'HONEY', 'OAK'], 'MEDIUM', 'LONG', '셰리 캐스크 숙성의 정수. 풍부한 드라이프루트와 초콜릿 풍미.', '맥캘란 12년 셰리오크 싱글몰트 스페이사이드 풍부한 건과일 캐러멜 바닐라 초콜릿 꿀 오크 셰리캐스크 달콤한', NOW(), NOW());
INSERT INTO whiskies (name_en, name_ko, image_file, alcohol_by_volume, style, country, region, price, nose_tags, palate_tags, body, aftertaste, description, embedding_text, created_at, updated_at) VALUES ('Lagavulin 16', '라가불린 16년', NULL, 43.0, 'Single Malt', 'Scotland', 'Islay', 110000, ARRAY['SMOKY', 'MARITIME', 'MEDICINAL'], ARRAY['SMOKY', 'PEPPER', 'OAK'], 'FULL', 'LONG', '아일라 피트 위스키의 대표주자. 강렬한 스모키향과 바다 내음.', '라가불린 16년 싱글몰트 아일라 강렬한 스모키 피트 바다 소금 약품향 후추 오크 풀바디 묵직한', NOW(), NOW());
INSERT INTO whiskies (name_en, name_ko, image_file, alcohol_by_volume, style, country, region, price, nose_tags, palate_tags, body, aftertaste, description, embedding_text, created_at, updated_at) VALUES ('Talisker 10', '탈리스커 10년', NULL, 45.8, 'Single Malt', 'Scotland', 'Islands', 65000, ARRAY['SMOKY', 'PEPPER', 'MARITIME'], ARRAY['CHILI', 'SMOKY', 'CITRUS'], 'MEDIUM', 'LONG', '바다와 연기의 조화. 후추같은 매콤한 피니시가 인상적.', '탈리스커 10년 싱글몰트 아일랜드 바다 연기 스모키 후추 매콤한 고추 시트러스 감귤', NOW(), NOW());
INSERT INTO whiskies (name_en, name_ko, image_file, alcohol_by_volume, style, country, region, price, nose_tags, palate_tags, body, aftertaste, description, embedding_text, created_at, updated_at) VALUES ('Glenmorangie Original', '글렌모렌지 오리지널', NULL, 40.0, 'Single Malt', 'Scotland', 'Highland', 52000, ARRAY['CITRUS', 'FLORAL', 'VANILLA'], ARRAY['HONEY', 'APPLE_PEAR', 'CREAMY'], 'LIGHT', 'MEDIUM', '섬세하고 우아한 하이랜드 몰트. 꽃향과 시트러스가 조화로움.', '글렌모렌지 오리지널 싱글몰트 하이랜드 섬세한 우아한 꽃향 플로럴 시트러스 바닐라 꿀 사과 크림 가벼운', NOW(), NOW());
INSERT INTO whiskies (name_en, name_ko, image_file, alcohol_by_volume, style, country, region, price, nose_tags, palate_tags, body, aftertaste, description, embedding_text, created_at, updated_at) VALUES ('Ardbeg 10', '아드벡 10년', NULL, 46.0, 'Single Malt', 'Scotland', 'Islay', 72000, ARRAY['SMOKY', 'CITRUS', 'MEDICINAL'], ARRAY['SMOKY', 'COFFEE', 'PEPPER'], 'FULL', 'LONG', '강렬하면서도 복합적인 피트 위스키. 레몬과 커피 뉘앙스.', '아드벡 10년 싱글몰트 아일라 강렬한 피트 스모키 레몬 시트러스 약품 커피 후추 복합적인', NOW(), NOW());
INSERT INTO whiskies (name_en, name_ko, image_file, alcohol_by_volume, style, country, region, price, nose_tags, palate_tags, body, aftertaste, description, embedding_text, created_at, updated_at) VALUES ('Balvenie 12 DoubleWood', '발베니 12년 더블우드', NULL, 40.0, 'Single Malt', 'Scotland', 'Speyside', 78000, ARRAY['HONEY', 'VANILLA', 'CINNAMON'], ARRAY['CARAMEL', 'NUTTY', 'OAK'], 'MEDIUM', 'MEDIUM', '버번 캐스크와 셰리 캐스크의 이중 숙성. 꿀과 바닐라의 조화.', '발베니 12년 더블우드 싱글몰트 스페이사이드 꿀 바닐라 시나몬 캐러멜 견과류 오크 달콤한 부드러운', NOW(), NOW());
INSERT INTO whiskies (name_en, name_ko, image_file, alcohol_by_volume, style, country, region, price, nose_tags, palate_tags, body, aftertaste, description, embedding_text, created_at, updated_at) VALUES ('Laphroaig 10', '라프로익 10년', NULL, 40.0, 'Single Malt', 'Scotland', 'Islay', 68000, ARRAY['SMOKY', 'MEDICINAL', 'MARITIME'], ARRAY['SMOKY', 'VANILLA', 'PEPPER'], 'FULL', 'LONG', '호불호가 갈리는 강렬한 피트. 약품향과 바다향이 특징.', '라프로익 10년 싱글몰트 아일라 피트 스모키 약품향 바다 해초 소금 강렬한 호불호', NOW(), NOW());
INSERT INTO whiskies (name_en, name_ko, image_file, alcohol_by_volume, style, country, region, price, nose_tags, palate_tags, body, aftertaste, description, embedding_text, created_at, updated_at) VALUES ('Highland Park 12', '하이랜드 파크 12년', NULL, 40.0, 'Single Malt', 'Scotland', 'Islands', 62000, ARRAY['HONEY', 'SMOKY', 'FLORAL'], ARRAY['CARAMEL', 'SMOKY', 'DRIED_FRUIT'], 'MEDIUM', 'MEDIUM', '은은한 피트와 꿀, 헤더 꽃향의 균형. 올라운더 위스키.', '하이랜드 파크 12년 싱글몰트 아일랜드 꿀 은은한 스모키 꽃향 캐러멜 건과일 균형잡힌 올라운더', NOW(), NOW());
INSERT INTO whiskies (name_en, name_ko, image_file, alcohol_by_volume, style, country, region, price, nose_tags, palate_tags, body, aftertaste, description, embedding_text, created_at, updated_at) VALUES ('Nikka From The Barrel', '닛카 프롬 더 배럴', NULL, 51.4, 'Blended', 'Japan', NULL, 58000, ARRAY['CARAMEL', 'VANILLA', 'CITRUS'], ARRAY['HONEY', 'OAK', 'PEPPER'], 'FULL', 'LONG', '높은 도수에서 오는 풍부한 맛. 가성비 좋은 일본 블렌디드.', '닛카 프롬 더 배럴 블렌디드 일본 캐러멜 바닐라 시트러스 꿀 오크 후추 풍부한 높은도수 가성비', NOW(), NOW());
INSERT INTO whiskies (name_en, name_ko, image_file, alcohol_by_volume, style, country, region, price, nose_tags, palate_tags, body, aftertaste, description, embedding_text, created_at, updated_at) VALUES ('Yamazaki 12', '야마자키 12년', NULL, 43.0, 'Single Malt', 'Japan', NULL, 180000, ARRAY['BERRY', 'FLORAL', 'VANILLA'], ARRAY['CHOCOLATE', 'CINNAMON', 'HONEY'], 'MEDIUM', 'LONG', '일본 싱글몰트의 상징. 딸기와 꽃향의 섬세한 풍미.', '야마자키 12년 싱글몰트 일본 딸기 베리 꽃향 플로럴 바닐라 초콜릿 시나몬 꿀 섬세한 우아한', NOW(), NOW());
INSERT INTO whiskies (name_en, name_ko, image_file, alcohol_by_volume, style, country, region, price, nose_tags, palate_tags, body, aftertaste, description, embedding_text, created_at, updated_at) VALUES ('Jameson', '제임슨', NULL, 40.0, 'Blended', 'Ireland', NULL, 32000, ARRAY['VANILLA', 'FLORAL', 'APPLE_PEAR'], ARRAY['CREAMY', 'VANILLA', 'HONEY'], 'LIGHT', 'SHORT', '부드럽고 가벼운 아이리시 위스키 입문용. 하이볼에 적합.', '제임슨 블렌디드 아이리시 아일랜드 부드러운 가벼운 바닐라 꽃향 사과 크림 꿀 입문용 하이볼', NOW(), NOW());
INSERT INTO whiskies (name_en, name_ko, image_file, alcohol_by_volume, style, country, region, price, nose_tags, palate_tags, body, aftertaste, description, embedding_text, created_at, updated_at) VALUES ('Monkey Shoulder', '몽키 숄더', NULL, 40.0, 'Blended Malt', 'Scotland', 'Speyside', 38000, ARRAY['VANILLA', 'HONEY', 'CITRUS'], ARRAY['MALT', 'CARAMEL', 'CREAMY'], 'LIGHT', 'SHORT', '가성비 좋은 블렌디드 몰트. 칵테일과 하이볼에 만능.', '몽키 숄더 블렌디드몰트 스페이사이드 바닐라 꿀 시트러스 몰트 캐러멜 크림 가벼운 가성비 하이볼 칵테일', NOW(), NOW());
INSERT INTO whiskies (name_en, name_ko, image_file, alcohol_by_volume, style, country, region, price, nose_tags, palate_tags, body, aftertaste, description, embedding_text, created_at, updated_at) VALUES ('Johnnie Walker Black Label', '조니워커 블랙라벨', NULL, 40.0, 'Blended', 'Scotland', NULL, 42000, ARRAY['SMOKY', 'DRIED_FRUIT', 'VANILLA'], ARRAY['CARAMEL', 'SMOKY', 'MALT'], 'MEDIUM', 'MEDIUM', '12년 숙성 블렌디드 스카치의 기준. 은은한 스모키향.', '조니워커 블랙라벨 블렌디드 스카치 스모키 건과일 바닐라 캐러멜 몰트 은은한 균형잡힌', NOW(), NOW());
INSERT INTO whiskies (name_en, name_ko, image_file, alcohol_by_volume, style, country, region, price, nose_tags, palate_tags, body, aftertaste, description, embedding_text, created_at, updated_at) VALUES ('Oban 14', '오반 14년', NULL, 43.0, 'Single Malt', 'Scotland', 'Highland', 95000, ARRAY['MARITIME', 'HONEY', 'CITRUS'], ARRAY['DRIED_FRUIT', 'OAK', 'SMOKY'], 'MEDIUM', 'LONG', '하이랜드와 아일라의 중간 지점. 바다향과 과일향의 조화.', '오반 14년 싱글몰트 하이랜드 바다 소금 꿀 시트러스 건과일 오크 스모키 해안가 균형잡힌', NOW(), NOW());
INSERT INTO whiskies (name_en, name_ko, image_file, alcohol_by_volume, style, country, region, price, nose_tags, palate_tags, body, aftertaste, description, embedding_text, created_at, updated_at) VALUES ('Dalmore 12', '달모어 12년', NULL, 40.0, 'Single Malt', 'Scotland', 'Highland', 75000, ARRAY['CHOCOLATE', 'CITRUS', 'CINNAMON'], ARRAY['CARAMEL', 'VANILLA', 'OAK'], 'MEDIUM', 'MEDIUM', '오렌지 마말레이드와 초콜릿의 풍미. 셰리 캐스크 피니시.', '달모어 12년 싱글몰트 하이랜드 초콜릿 오렌지 시트러스 시나몬 캐러멜 바닐라 오크 셰리캐스크 달콤한', NOW(), NOW());
INSERT INTO whiskies (name_en, name_ko, image_file, alcohol_by_volume, style, country, region, price, nose_tags, palate_tags, body, aftertaste, description, embedding_text, created_at, updated_at) VALUES ('Bowmore 12', '보모어 12년', NULL, 40.0, 'Single Malt', 'Scotland', 'Islay', 60000, ARRAY['SMOKY', 'HONEY', 'CITRUS'], ARRAY['SMOKY', 'VANILLA', 'TROPICAL'], 'MEDIUM', 'MEDIUM', '아일라 입문용. 부드러운 피트와 열대과일의 균형.', '보모어 12년 싱글몰트 아일라 부드러운 피트 스모키 꿀 시트러스 바닐라 열대과일 균형잡힌 입문용', NOW(), NOW());
INSERT INTO whiskies (name_en, name_ko, image_file, alcohol_by_volume, style, country, region, price, nose_tags, palate_tags, body, aftertaste, description, embedding_text, created_at, updated_at) VALUES ('Hibiki Harmony', '히비키 하모니', NULL, 43.0, 'Blended', 'Japan', NULL, 120000, ARRAY['FLORAL', 'HONEY', 'VANILLA'], ARRAY['CARAMEL', 'APPLE_PEAR', 'OAK'], 'LIGHT', 'MEDIUM', '일본 블렌디드의 정수. 섬세하고 조화로운 맛.', '히비키 하모니 블렌디드 일본 꽃향 플로럴 꿀 바닐라 캐러멜 사과 오크 섬세한 조화로운 우아한', NOW(), NOW());
INSERT INTO whiskies (name_en, name_ko, image_file, alcohol_by_volume, style, country, region, price, nose_tags, palate_tags, body, aftertaste, description, embedding_text, created_at, updated_at) VALUES ('Buffalo Trace', '버팔로 트레이스', NULL, 45.0, 'Bourbon', 'USA', 'Kentucky', 35000, ARRAY['CARAMEL', 'VANILLA', 'CINNAMON'], ARRAY['HONEY', 'OAK', 'NUTTY'], 'MEDIUM', 'MEDIUM', '가성비 좋은 버번 입문용. 캐러멜과 바닐라의 달콤함.', '버팔로 트레이스 버번 켄터키 미국 캐러멜 바닐라 시나몬 꿀 오크 견과류 달콤한 가성비 입문용', NOW(), NOW());
INSERT INTO whiskies (name_en, name_ko, image_file, alcohol_by_volume, style, country, region, price, nose_tags, palate_tags, body, aftertaste, description, embedding_text, created_at, updated_at) VALUES ('Makers Mark', '메이커스 마크', NULL, 45.0, 'Bourbon', 'USA', 'Kentucky', 38000, ARRAY['CARAMEL', 'VANILLA', 'BERRY'], ARRAY['HONEY', 'CREAMY', 'CINNAMON'], 'MEDIUM', 'MEDIUM', '밀 원료 특유의 부드러움. 달콤하고 크리미한 버번.', '메이커스 마크 버번 켄터키 미국 캐러멜 바닐라 베리 꿀 크림 시나몬 달콤한 부드러운 크리미한', NOW(), NOW());

-- Users
INSERT INTO users (nickname, email, profile_image, oauth_provider, oauth_id, reminder_enabled, created_at, updated_at) VALUES ('위스키초보', 'user01@test.com', 'default.png', 'kakao', 'kakao_001', false, NOW(), NOW());
INSERT INTO users (nickname, email, profile_image, oauth_provider, oauth_id, reminder_enabled, created_at, updated_at) VALUES ('싱글몰트러버', 'user02@test.com', 'default.png', 'kakao', 'kakao_002', false, NOW(), NOW());
INSERT INTO users (nickname, email, profile_image, oauth_provider, oauth_id, reminder_enabled, created_at, updated_at) VALUES ('피트매니아', 'user03@test.com', 'default.png', 'naver', 'naver_001', false, NOW(), NOW());
INSERT INTO users (nickname, email, profile_image, oauth_provider, oauth_id, reminder_enabled, created_at, updated_at) VALUES ('하이볼장인', 'user04@test.com', 'default.png', 'naver', 'naver_002', false, NOW(), NOW());
INSERT INTO users (nickname, email, profile_image, oauth_provider, oauth_id, reminder_enabled, created_at, updated_at) VALUES ('버번킹', 'user05@test.com', 'default.png', 'google', 'google_001', false, NOW(), NOW());
INSERT INTO users (nickname, email, profile_image, oauth_provider, oauth_id, reminder_enabled, created_at, updated_at) VALUES ('위스키탐험가', 'user06@test.com', 'default.png', 'google', 'google_002', false, NOW(), NOW());
INSERT INTO users (nickname, email, profile_image, oauth_provider, oauth_id, reminder_enabled, created_at, updated_at) VALUES ('니트파', 'user07@test.com', 'default.png', 'kakao', 'kakao_003', false, NOW(), NOW());
INSERT INTO users (nickname, email, profile_image, oauth_provider, oauth_id, reminder_enabled, created_at, updated_at) VALUES ('드람한잔', 'user08@test.com', 'default.png', 'kakao', 'kakao_004', false, NOW(), NOW());
INSERT INTO users (nickname, email, profile_image, oauth_provider, oauth_id, reminder_enabled, created_at, updated_at) VALUES ('아일라덕후', 'user09@test.com', 'default.png', 'naver', 'naver_003', false, NOW(), NOW());
INSERT INTO users (nickname, email, profile_image, oauth_provider, oauth_id, reminder_enabled, created_at, updated_at) VALUES ('캐스크헌터', 'user10@test.com', 'default.png', 'naver', 'naver_004', false, NOW(), NOW());
INSERT INTO users (nickname, email, profile_image, oauth_provider, oauth_id, reminder_enabled, created_at, updated_at) VALUES ('위스키노트', 'user11@test.com', 'default.png', 'google', 'google_003', false, NOW(), NOW());
INSERT INTO users (nickname, email, profile_image, oauth_provider, oauth_id, reminder_enabled, created_at, updated_at) VALUES ('스모키좋아', 'user12@test.com', 'default.png', 'google', 'google_004', false, NOW(), NOW());
INSERT INTO users (nickname, email, profile_image, oauth_provider, oauth_id, reminder_enabled, created_at, updated_at) VALUES ('셰리캐스크', 'user13@test.com', 'default.png', 'kakao', 'kakao_005', false, NOW(), NOW());
INSERT INTO users (nickname, email, profile_image, oauth_provider, oauth_id, reminder_enabled, created_at, updated_at) VALUES ('온더락스', 'user14@test.com', 'default.png', 'kakao', 'kakao_006', false, NOW(), NOW());
INSERT INTO users (nickname, email, profile_image, oauth_provider, oauth_id, reminder_enabled, created_at, updated_at) VALUES ('위린이', 'user15@test.com', 'default.png', 'naver', 'naver_005', false, NOW(), NOW());
INSERT INTO users (nickname, email, profile_image, oauth_provider, oauth_id, reminder_enabled, created_at, updated_at) VALUES ('몰트위저드', 'user16@test.com', 'default.png', 'naver', 'naver_006', false, NOW(), NOW());
INSERT INTO users (nickname, email, profile_image, oauth_provider, oauth_id, reminder_enabled, created_at, updated_at) VALUES ('테이스팅킹', 'user17@test.com', 'default.png', 'google', 'google_005', false, NOW(), NOW());
INSERT INTO users (nickname, email, profile_image, oauth_provider, oauth_id, reminder_enabled, created_at, updated_at) VALUES ('바텐더지망', 'user18@test.com', 'default.png', 'google', 'google_006', false, NOW(), NOW());
INSERT INTO users (nickname, email, profile_image, oauth_provider, oauth_id, reminder_enabled, created_at, updated_at) VALUES ('위스키수집가', 'user19@test.com', 'default.png', 'kakao', 'kakao_007', false, NOW(), NOW());
INSERT INTO users (nickname, email, profile_image, oauth_provider, oauth_id, reminder_enabled, created_at, updated_at) VALUES ('드람마스터', 'user20@test.com', 'default.png', 'kakao', 'kakao_008', false, NOW(), NOW());

-- Wishlists
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (1, 2, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (2, 2, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (3, 2, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (5, 2, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (7, 2, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (8, 2, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (10, 2, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (13, 2, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (14, 2, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (15, 2, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (18, 2, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (20, 2, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (1, 11, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (2, 11, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (4, 11, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (6, 11, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (8, 11, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (11, 11, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (13, 11, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (16, 11, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (17, 11, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (19, 11, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (3, 3, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (6, 3, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (7, 3, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (9, 3, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (12, 3, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (16, 3, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (17, 3, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (20, 3, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (1, 1, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (4, 1, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (8, 1, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (11, 1, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (14, 1, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (15, 1, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (19, 1, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (2, 18, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (5, 18, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (10, 18, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (13, 18, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (17, 18, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (20, 18, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (2, 7, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (10, 7, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (13, 7, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (19, 7, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (4, 13, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (15, 13, NOW());
INSERT INTO wishlists (user_id, whisky_id, created_at) VALUES (18, 13, NOW());